{
  lib,
  config,
  ...
}:
let
  cfg = config.opt.prusaslicer.printers.elrond;
in
{
  options = {
    opt.prusaslicer.printers.elrond = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Enable Elrond";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    home.file = {
      ".config/PrusaSlicer/physical_printer/Elrond.ini".text = ''
        # generated by Home Manager
        host_type = moonraker
        preset_name = Elrond
        preset_names = Elrond
        print_host = elrond.printer.local
        printer_technology = FFF
        printhost_apikey =
        printhost_authorization_type = key
        printhost_cafile =
        printhost_password =
        printhost_port =
        printhost_ssl_ignore_revoke = 0
        printhost_user =
      '';
      ".config/PrusaSlicer/printer/Elrond.ini".text = ''
        # generated by Home Manager
        autoemit_temperature_commands = 0
        bed_custom_model =
        bed_custom_texture =
        bed_shape = 0x0,250x0,250x210,0x210
        before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
        between_objects_gcode =
        binary_gcode = 0
        color_change_gcode = M600\nG1 E0.3 F1500 ; prime after color change
        cooling_tube_length = 5
        cooling_tube_retraction = 91.5
        default_filament_profile = "Prusament PLA"
        default_print_profile = 0.15mm QUALITY @MK3
        deretract_speed = 0
        end_gcode = PRINT_END
        extra_loading_move = -2
        extruder_clearance_height = 20
        extruder_clearance_radius = 45
        extruder_colour = ""
        extruder_offset = 0x0
        gcode_flavor = klipper
        high_current_on_filament_swap = 0
        host_type = prusalink
        inherits = Original Prusa i3 MK3S & MK3S+
        layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
        machine_limits_usage = time_estimate_only
        machine_max_acceleration_e = 5000,5000
        machine_max_acceleration_extruding = 1250,1250
        machine_max_acceleration_retracting = 1250,1250
        machine_max_acceleration_travel = 1500,1250
        machine_max_acceleration_x = 1000,960
        machine_max_acceleration_y = 1000,960
        machine_max_acceleration_z = 200,200
        machine_max_feedrate_e = 120,120
        machine_max_feedrate_x = 200,100
        machine_max_feedrate_y = 200,100
        machine_max_feedrate_z = 12,12
        machine_max_jerk_e = 4.5,4.5
        machine_max_jerk_x = 8,8
        machine_max_jerk_y = 8,8
        machine_max_jerk_z = 0.4,0.4
        machine_min_extruding_rate = 0,0
        machine_min_travel_rate = 0,0
        max_layer_height = 0.25
        max_print_height = 210
        min_layer_height = 0.07
        multimaterial_purging = 140
        nozzle_diameter = 0.4
        nozzle_high_flow = 0
        parking_pos_retraction = 92
        pause_print_gcode = M601
        prefer_clockwise_movements = 0
        print_host =
        printer_model = MK3S
        printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
        printer_settings_id =
        printer_technology = FFF
        printer_variant = 0.4
        printer_vendor =
        printhost_apikey =
        printhost_cafile =
        remaining_times = 1
        retract_before_travel = 1
        retract_before_wipe = 0%
        retract_layer_change = 1
        retract_length = 0.8
        retract_length_toolchange = 4
        retract_lift = 0.4
        retract_lift_above = 0
        retract_lift_below = 209
        retract_restart_extra = 0
        retract_restart_extra_toolchange = 0
        retract_speed = 35
        silent_mode = 0
        single_extruder_multi_material = 0
        start_gcode = PRINT_START BED=[first_layer_bed_temperature] EXTRUDER=[first_layer_temperature]
        template_custom_gcode =
        thumbnails = 48x48/PNG, 300x300/PNG
        thumbnails_format = PNG
        toolchange_gcode =
        travel_lift_before_obstacle = 0
        travel_max_lift = 0
        travel_ramping_lift = 0
        travel_slope = 0
        use_firmware_retraction = 0
        use_relative_e_distances = 1
        use_volumetric_e = 0
        variable_layer_height = 1
        wipe = 1
        z_offset = 0
      '';
    };
  };
}
